# Generated by Django 3.2.15 on 2022-10-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
