# Generated by Django 3.2.15 on 2023-05-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
